### ISSUE TITLE
代码中不明白的一行

### ISSUE THREAD

**Issue by moonyoung430** [RDShi/voiceprint#5]
您好：
首先非常感谢您的工作，我在理解代码过程中有一个地方始终没搞明白：
![default](https://user-images.githubusercontent.com/31330980/51299352-279a0300-1a63-11e9-9331-79340fa602e0.png)
train_model.py中的187行左右
embsp = sess.run(embeddings, feed_dict={x_b: test_feats[args.batch_size-len(enroll_feats):], keep_prob: 1})
embeddings要求输入的x_b大小必须是batch_size维度的，对吧？
这里feed的test_feats[args.batch_size-len(enroll_feats):]的大小肯定不是batch_size啊？
源代码batch_size=128 我修改了一下之后这里一直报错，由于我自己的数据集比较小，对test_file的选取的一些参数我都改小了，但是即便是原始的参数，我计算了一下，也不对啊
不知道我不是哪里理解错了

**Comment by RDShi** [comment]
x_b 并不是一定是 batch_size 大小，可以是随便的大小。batch_size 的意思是队列会 batch_size 的个数给 x_b 数据，希望能帮到你。

**Comment by moonyoung430** [comment]
报错：
![default](https://user-images.githubusercontent.com/31330980/51310091-d39e1700-1a80-11e9-9648-667293c26f96.png)
错误指向：
![default](https://user-images.githubusercontent.com/31330980/51310173-12cc6800-1a81-11e9-97da-ed544e0bf1ea.png)

x_b 创建方法：
![default](https://user-images.githubusercontent.com/31330980/51310213-2a0b5580-1a81-11e9-8b11-acaa1b2d5c4b.png)


我改了batch_size大小为16 ，运行到这里就会报错，batch_size - len(enroll_feat) 大小为14
那这是什么原因呢？

**Comment by moonyoung430** [comment]
我还改动了  util.py 中的get_test_batch,因为我自己数据集没有那么大，所以筛选样本的参数都相应调小了，所以：
test_feats[args.batch_size-len(enroll_feats):] 的维度是（14，199，40）

**Comment by RDShi** [comment]
好久没看代码，刚说错了，x_b 得是 batch_size 大小的，那块的逻辑是用 enroll 的数据加上 test 的数据一共组成两个 batch，所以不能直接只 feed test_feats，得补齐

**Comment by moonyoung430** [comment]
我之一没有调通，还在努力中。
但是对于您的这个训练逻辑我还是有点不清楚。
首先在数据库里选择了一些作为test_file，训练数据是除掉test_file的其他数据，最后在evaluate_step的时候，enroll和test不都是从test_file中选择的吗？为什么要分成enroll和test两个部分拼到一起来预测呢？

**Comment by RDShi** [comment]
说话人识别的问题和其他分类问题略有不同，训练其实是训练一种 embedding 的函数，enroll 的数据是某个说话人的注册数据，他未必存在于训练数据中。这的逻辑是某几个人有一些注册数据，我们来看其他部分的数据是否能分类准确。你应该是把这个问题当作是普通的分类问题了。

**Comment by moonyoung430** [comment]
哦那我明白了，是针对训练数据来训练一个embedding的过程，然后测试的时候，将enroll和test都embedding之后来对比是不是同一个人。  这样理解对吧

**Comment by RDShi** [comment]
是的
